### ISSUE TITLE
Apply redux-devtools-extension as middleware

### ISSUE THREAD

**Issue by KajiTetsushi** [CraigBeswetherick/Typescript-phaser3-react-redux-boilerplate#3]
Hi, @CraigBeswetherick. Found your repository from your post at [HTML5 Game Devs](http://www.html5gamedevs.com/topic/42441-phaser-3-boilerplate-using-react-redux-sass-typescript-eslint/) ([Google's backup copy](http://webcache.googleusercontent.com/search?q=cache:zVtmw1VsVQwJ:www.html5gamedevs.com/topic/42441-phaser-3-boilerplate-using-react-redux-sass-typescript-eslint/+&cd=3&hl=en&ct=clnk&gl=my)).

----
### Let me get this out of the way.
Massive, **massive** thank you for bringing us this example! I've got a `react` background with almost zero experience in game development. I just started picking up `phaser` about half a day ago, but right now I didn't want to leave my current background too much because React for the non-`<canvas>` UI layer is just too good to pass. Glad to know that someone else out there has similar concerns.

----
### Straight to the point now.
I've noticed that the example doesn't have [`redux-devtools-extension`](https://github.com/zalmoxisus/redux-devtools-extension). I won't pretend that I know anything about the performance impact logging will have on the game, but at least on development, I feel that it's added value to be able to see state changes as they happen. 

Get what i mean?

**[src/index.tsx](https://github.com/CraigBeswetherick/Typescript-phaser3-react-redux-boilerplate/blob/master/src/index.tsx)**
```js
import React from 'react';
import ReactDOM from 'react-dom';
import { composeWithDevTools } from 'redux-devtools-extension'; // For state logging

import './index.scss';
import App from './App';
import * as serviceWorker from './serviceWorker';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware } from 'redux';
import { reducers } from './reducers/index';

const store = createStore(
  reducers,
  undefined,
  // Allows us to observe state changes directly
  // on the browser with the Redux DevTools extension
  composeWithDevTools(
    applyMiddleware()
  )
);

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

```

**Comment by CraigBeswetherick** [comment]
Hey, thanks for this! And sorry for taking so long to respond. I will definitely add this to the project - I have actually encountered a problem in a previous project that was created by using the redux dev tools, yet it was an extreme edge case and should not affect most users. Feel free to make a PR if you like. There are some other integrations I plan to make as well, but if you have any more requests please let me know. 

Thanks!

**Comment by KajiTetsushi** [comment]
> Feel free to make a PR if you like.

PR now at #4.

> [...] if you have any more requests please let me know.

Nothing comes to mind at the moment, but yep, sure.
